### ISSUE TITLE
test-non-mruby.rb: undefined method `units' for #<OSC::RemoteMetadata:0x000055f8b9ed9df8>

### ISSUE THREAD

**Issue by nick87720z** [mruby-zest/mruby-qml-spawn#3]
When running `ruby test-non-mruby.rb`, which is invoked by make rtest, from mruby-zest-build, it fails with this:
```
ok 13 - Unchanged properties use defaults...
ok 14 - Changed parameters update...
ok 15 - Changed parameters update using dependency graph...
ok 16 - Proxy Objects are provided to children...
# 0 test(s) failed out of 16 (currently passing 100.0% tests)
anonymous-Valuator:30:in `block in initialize': undefined method `units' for #<OSC::RemoteMetadata:0x000055f8b9ed9df8> (NoMethodError)
	from /var/calculate/tmp/portage/media-sound/zynaddsubfx-3.0.3-r1/work/mruby-zest-build/src/mruby-qml-spawn/mrblib/database.rb:148:in `write_property'
	from /var/calculate/tmp/portage/media-sound/zynaddsubfx-3.0.3-r1/work/mruby-zest-build/src/mruby-qml-spawn/mrblib/build.rb:623:in `block in attr_property'
	from anonymous-ZynHeaderParams:26:in `initialize'
	from anonymous-ZynHeader:12:in `new'
	from anonymous-ZynHeader:12:in `initialize'
	from anonymous-MainWindow:9:in `new'
	from anonymous-MainWindow:9:in `initialize'
	from /var/calculate/tmp/portage/media-sound/zynaddsubfx-3.0.3-r1/work/mruby-zest-build/src/mruby-qml-spawn/mrblib/build.rb:753:in `new'
	from /var/calculate/tmp/portage/media-sound/zynaddsubfx-3.0.3-r1/work/mruby-zest-build/src/mruby-qml-spawn/mrblib/build.rb:753:in `block in doTest'
	from /var/calculate/tmp/portage/media-sound/zynaddsubfx-3.0.3-r1/work/mruby-zest-build/src/mruby-qml-spawn/mrblib/build.rb:750:in `each'
	from /var/calculate/tmp/portage/media-sound/zynaddsubfx-3.0.3-r1/work/mruby-zest-build/src/mruby-qml-spawn/mrblib/build.rb:750:in `doTest'
	from test-non-mruby.rb:66:in `<main>'
```
Full log: https://gist.github.com/nick87720z/31071bb60e89f15fbc01a78da2c323a3

**Comment by fundamental** [comment]
Fixed in current revision
